kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-permissive
  namespace: ns-demo
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - permissive
    verbs:
      - use