apiVersion: apps/v1
kind: Deployment
metadata:
  name: priv-nginx-deployment
  namespace: ns-demo
spec:
  selector:
    matchLabels:
      app: priv-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: priv-nginx
    spec:
      serviceAccountName: nginx
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
      hostNetwork: true