apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-restrictive
  namespace: ns-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-restrictive
subjects:
- kind: ServiceAccount
  name: nginx
  namespace: ns-demo