---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-sa
  namespace: app-test
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80