apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx-deployment
  namespace: ns-demo
spec:
  selector:
    matchLabels:
      app: simple-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      serviceAccountName: nginx-restrictive
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80          